Delete pstdint.h, and always use <stdint.h>
Looks like MSVC has included a <stdint.h> since VS2010.

Fixes e.g.:

pstdint.h(383): error C2371: 'uint32_t': redefinition; different basic types